Highcharts.chart('paladin_retribution_patchwerk', 
{
    chart: {
        type: "bar"
    },
    legend: {
        align: "right",
        backgroundColor: (Highcharts.theme && Highcharts.theme.background2) || 'white',
        borderColor: "#CCC",
        borderWidth: 1,
        floating: false,
        reversed: true,
        shadow: false,
        verticalAlign: "bottom",
        x: 0,
        y: 0
    },
    plotOptions: {
        bar: {
            dataLabels: {
                color: (Highcharts.theme && Highcharts.theme.dataLabelsColor) || 'white',
                enabled: false
            },
            point: {
                events: {
                    click: function (event) {                var chart = this.series.yAxis;                chart.removePlotLine('helperLine');                chart.addPlotLine({                    value: this.stackY,                    color: '#000',                    width: 2,                    id: 'helperLine',                    zIndex: 5,                    label: {                      text: this.series.name + ' ' + this.category,                      align: 'left',                      verticalAlign: 'bottom',                      rotation: 0,                      y: -5                    }                });              }
                }
            },
            stacking: "normal"
        },
        series: {
            borderColor: "#151515",
            events: {
                legendItemClick: function() { return false; }
            }
        }
    },
    series: [
        {
            color: "#ffeb3b",
            data: [
                130230,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0,
                0
            ],
            name: "970"
        },
        {
            color: "#00E676",
            data: [
                0,
                9371,
                9174,
                6043,
                7324,
                2172,
                7587,
                5120,
                7348,
                7371,
                6465,
                5608,
                5183,
                6346,
                7144,
                5208,
                5956,
                7384,
                6580,
                6838,
                5608,
                4596,
                6603,
                6971,
                7508,
                6260,
                4954,
                0,
                5029,
                7433,
                5632,
                6684,
                6828,
                0,
                1650,
                0,
                4013,
                2163,
                8458,
                3672,
                3353,
                2540,
                2432,
                3134,
                2047,
                2528
            ],
            name: "940"
        },
        {
            color: "#db843d",
            data: [
                0,
                9673,
                8031,
                7771,
                7365,
                4492,
                6336,
                7045,
                6175,
                6606,
                5594,
                6733,
                5653,
                5702,
                4316,
                4402,
                6249,
                4984,
                5581,
                5046,
                4898,
                5117,
                7919,
                4497,
                4645,
                4458,
                6704,
                6020,
                4631,
                5123,
                4895,
                5257,
                6887,
                0,
                4285,
                0,
                4015,
                2064,
                6894,
                2366,
                1629,
                2396,
                2547,
                1749,
                1611,
                543
            ],
            name: "930"
        },
        {
            color: "#4198af",
            data: [
                0,
                8912,
                9157,
                6909,
                6061,
                3770,
                6013,
                6279,
                5696,
                4678,
                5248,
                5158,
                7683,
                5485,
                6757,
                5346,
                5039,
                6027,
                5238,
                5824,
                5836,
                6771,
                5287,
                3459,
                7355,
                6267,
                4499,
                4784,
                4515,
                5856,
                3095,
                6726,
                3874,
                0,
                5848,
                0,
                2103,
                2453,
                7406,
                2909,
                3844,
                3229,
                2630,
                1035,
                1894,
                1822
            ],
            name: "920"
        },
        {
            color: "#71588f",
            data: [
                0,
                5780,
                6597,
                5506,
                5519,
                3467,
                5809,
                5589,
                5216,
                5551,
                5701,
                4718,
                4293,
                5934,
                5490,
                3287,
                5742,
                4198,
                4476,
                3874,
                5648,
                4810,
                6101,
                6133,
                5369,
                2163,
                4495,
                4973,
                4935,
                5769,
                3707,
                3088,
                5612,
                0,
                2616,
                0,
                2769,
                2353,
                6218,
                2428,
                1565,
                2360,
                2952,
                2167,
                919,
                1285
            ],
            name: "910"
        },
        {
            color: "#89a54e",
            data: [
                0,
                75763,
                6548,
                4181,
                5698,
                3996,
                4138,
                5010,
                4273,
                3340,
                5006,
                5341,
                3705,
                4511,
                3464,
                3360,
                4401,
                5829,
                4613,
                4984,
                4211,
                3412,
                5209,
                4610,
                4713,
                5137,
                3898,
                3318,
                4100,
                3592,
                3455,
                5966,
                4219,
                3800,
                1947,
                3233,
                4145,
                2250,
                3748,
                3482,
                3083,
                983,
                1363,
                2377,
                2429,
                2171
            ],
            name: "900"
        },
        {
            color: "#aa4643",
            data: [
                0,
                0,
                66572,
                4568,
                68846,
                1602,
                4839,
                64185,
                5224,
                63369,
                3557,
                4581,
                4977,
                4363,
                4911,
                3289,
                3340,
                4163,
                4044,
                4945,
                5268,
                5007,
                5017,
                3996,
                5255,
                55068,
                4199,
                58885,
                3630,
                4832,
                3025,
                3530,
                3611,
                5123,
                4173,
                4675,
                1369,
                1811,
                7012,
                1860,
                1675,
                2091,
                1791,
                1144,
                971,
                1701
            ],
            name: "890"
        },
        {
            color: "#4572a7",
            data: [
                0,
                0,
                0,
                67913,
                0,
                81069,
                59755,
                0,
                57419,
                0,
                58003,
                57274,
                57882,
                56860,
                57023,
                63799,
                57948,
                55511,
                54626,
                53239,
                52780,
                52505,
                46056,
                51372,
                45026,
                0,
                50156,
                0,
                49219,
                42509,
                49693,
                42021,
                41684,
                60889,
                42837,
                53869,
                40661,
                44617,
                15645,
                34699,
                35874,
                32140,
                31794,
                30712,
                28150,
                26628
            ],
            name: "880"
        }
    ],
    subtitle: {
        text: "UTC 2017-09-22 18:32 SimC build: <a href=\"https://github.com/simulationcraft/simc/commit/241e09d6aeb2f51f8b24e2b7038b7dc580223b38\" target=\"blank\">241e09d</a>"
    },
    title: {
        text: "Paladin - Retribution - Patchwerk"
    },
    tooltip: {
        backgroundColor: "#eee",
        borderColor: "#bbb",
        formatter: function() {        var s = '<b>'+ this.x +'</b>';        var cumulative_amount = 0;        for (var i = this.points.length - 1 ; i >= 0 ; i--) {            cumulative_amount += this.points[i].y;            if (this.points[i].y !== 0){                s += '<br/><span style=\"color: ' + this.points[i].series.color + '; font-weight: bold;\">' + this.points[i].series.name +'</span>: ' + cumulative_amount;            }        }        return s;      },
        headerFormat: "<b>{point.x}</b>",
        shared: true,
        style: {
            color: "black"
        }
    },
    xAxis: {
        categories: [
            "Kil'jaeden's Burning Wish",
            "Specter of Betrayal",
            "Vial of Ceaseless Toxins",
            "Eye of Command",
            "Infernal Cinders",
            "Unstable Arcanocrystal",
            "Horn of Valor",
            "Cradle of Anguish",
            "Chaos Talisman",
            "Engine of Eradication",
            "Ettin Fingernail",
            "Stat Stick (Crit)",
            "Entwined Elemental Foci",
            "Stat Stick (Mastery)",
            "Stat Stick (Versatility)",
            "Convergence of Fates",
            "Memento of Angerboda",
            "Stat Stick (Haste)",
            "Faulty Countermeasure",
            "Chrono Shard",
            "Fel-Oiled Infernal Machine",
            "Nightmare Egg Shell",
            "Claw of the Crystalline Scorpid",
            "PVP Badge of Victory",
            "Bloodstained Handkerchief",
            "Umbral Moonglaives",
            "Gift of Radiance",
            "Astral Alchemist Stone",
            "PVP Insignia of Victory",
            "Might of Krosus",
            "The Devilsaur's Bite",
            "Ursoc's Rending Paw",
            "Void Stalker's Contract",
            "Darkmoon Deck: Dominion",
            "Spontaneous Appendages",
            "Infernal Alchemist Stone",
            "Terrorbound Nexus",
            "Nature's Call",
            "Draught of Souls",
            "Spiked Counterweight",
            "Mark of Dargrul",
            "Tiny Oozeling in a Jar",
            "Toe Knee's Promise",
            "Windscar Whetstone",
            "Giant Ornamental Pearl",
            "Ravaged Seed Pod"
        ]
    },
    yAxis: {
        labels: {
            enabled: false
        },
        min: 0,
        plotLines: [
            {
                color: "#1E90FF",
                label: {
                    align: "left",
                    rotation: -90,
                    style: {
                        color: "#1E90FF"
                    },
                    text: "mean at 78182",
                    verticalAlign: "bottom",
                    x: 10,
                    y: -25
                },
                value: 78182.04347826086,
                width: 2,
                zIndex: 2
            }
        ],
        stackLabels: {
            enabled: false,
            formatter: function() {            /* I need to figure out how to get the mean value here,            ** to allow the percent diff to mean as label            ** console.log(this); */            return;          },
            style: {
                color: (Highcharts.theme && Highcharts.theme.textColor) || 'white',
                fontWeight: "bold"
            }
        },
        title: {
            text: "\u0394 Damage per second"
        }
    }
});